### ISSUE TITLE
Does powerbi-cilent-angular library supports server side rendering?

### ISSUE THREAD

**Issue by SarangNasare01** [microsoft/powerbi-client-angular#44] opened 2023-09-01 12:57 UTC
We have an angular application in which we are using powerbi-cilent-angular library for embedding power bi report. the application is running fine when we locally run it. When we are building SSR (Server side Rendering) package to deploy on the node. Package is getting successfully build but when we deploy it on node it does not work and gives below error. 
If we build SSR (Server side Rendering) package after commenting out powerbi-cilent-angular library that package works on the node but then obviously embedding report functionality does not work.
So Does powerbi-cilent-angular library supports server side rendering?

![image](https://github.com/microsoft/powerbi-client-angular/assets/133002664/b9f7501e-71b5-411a-b77b-fa643f34466d)

**Comment by rad10wave** [comment] 2023-09-08 11:46
The `powerbi-cilent-angular` library doesn't support server-side rendering, this library relies on window reference, which cannot be used in server-side rendering.

There are few potential solution for addressing this issue:
- Add a condition to check if window object exists before using the code. But it will skip the line of codes which relies on window object.
- Another approach will be to use dynamic import or lazy loading. It will make sure that the code is executed only in the browser, where window object is present.

**Comment by may-hartov** [comment] 2024-02-08 09:05
Behavior is expected by design, server-side rendering is not supported. Closing the issue.

**Closed by may-hartov** 2024-02-08 09:05 UTC
